// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6uE5WgeyrQDqRfYzmq_4ndNqmgWvSFy0',
    appId: '1:798493430076:web:67d87f83d7cb1244f58e39',
    messagingSenderId: '798493430076',
    projectId: 'soothesync-3fc95',
    authDomain: 'soothesync-3fc95.firebaseapp.com',
    storageBucket: 'soothesync-3fc95.firebasestorage.app',
    measurementId: 'G-68FYMD248Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBycYKnN_69C_WkHicMXe0IdREtHUZcsn8',
    appId: '1:798493430076:android:40c749a0f6eed3def58e39',
    messagingSenderId: '798493430076',
    projectId: 'soothesync-3fc95',
    storageBucket: 'soothesync-3fc95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxW2fRna1J467HD99iaE3gEv_M3Ds-f0w',
    appId: '1:798493430076:ios:d4b83de451977b94f58e39',
    messagingSenderId: '798493430076',
    projectId: 'soothesync-3fc95',
    storageBucket: 'soothesync-3fc95.firebasestorage.app',
    iosBundleId: 'com.example.soothesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxW2fRna1J467HD99iaE3gEv_M3Ds-f0w',
    appId: '1:798493430076:ios:d4b83de451977b94f58e39',
    messagingSenderId: '798493430076',
    projectId: 'soothesync-3fc95',
    storageBucket: 'soothesync-3fc95.firebasestorage.app',
    iosBundleId: 'com.example.soothesync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6uE5WgeyrQDqRfYzmq_4ndNqmgWvSFy0',
    appId: '1:798493430076:web:7ecfe66031baaff5f58e39',
    messagingSenderId: '798493430076',
    projectId: 'soothesync-3fc95',
    authDomain: 'soothesync-3fc95.firebaseapp.com',
    storageBucket: 'soothesync-3fc95.firebasestorage.app',
    measurementId: 'G-1XV10TBRSE',
  );
}
